Dev
niki-gor/matrix-calculator pull request #1
Opened 2022-10-22 16:20 UTC by niki-gor

2022-10-30 12:06 UTC, DPeshkoff requested changes
Привет! Посмотрел решение, есть замечания.
Предварительная таблица с баллами (в критериях указан балл за эту фичу, если бы проект собирался. Я не поленился и склонировал к себе, проект не собрался, поэтому пока что за такое в сумме только 0)

Кроме того, отсутствует CI, за все критерии только половина баллов (учтено в таблице)

| Критерий | Предварительный балл | Максимальный балл | Комментарий |
|---|---|---|---|
| 1) обращение по индексам к элементам, извлечение диагонали, строки или столбца | 0.25 | 1 | Не покрыто тестами, отсутствует CI |
| 2) возможность создания матрицы из векторов или чисел, вектора из чисел | 0 | 1 | Кажется, создать матрицу из векторов и вектор из чисел нельзя (векторов как будто бы вообще нет). Отсутствуют тесты, отсутствует CI |
| 3) поэлементное сложение/вычитание/умножение объектов одинаковой размерности  | 0 | 1 | аналогично |
| 4) умножение числа на матрицу, вектора на матрицу, матрицы на вектор и матрицы на матрицу | 0 | 1 | Кажется, векторов нет. Отсутствуют тесты, отсутствует CI |
| 5) суммирование/вычитание числа и вектора/матрицы, матрицы и вектора (с возможностью выбора - по строкам/по столбцам) | 0 | 1 | Векторов нет. Отсутствуют тесты, отсутствует CI |
| 6) получение транспонированной и обратной матриц | 0.15 | 1 | Обратной матрицы нет. Отсутствуют тесты. |
| 7) подсчёт определителя матрицы | 0.5 | 1 | Отсутствует CI |
|---|---|---|---|
| Дополнительно: поддержка слайсов | 0.25 | 1 | Не покрыто тестами, отсутствует CI |
| Дополнительно: шаблонные параметры  | 0 | 2 | Нет векторов. Отсутствуют тесты, отсутствует CI |
|---|---|---|---|
| Σ  | 0 | 10 | проект не собирается вообще |

Неделя на исправление замечаний: дедлайн 6 ноября

2022-10-30 12:06 UTC, DPeshkoff commented on Dockerfile
> +FROM leshiy1295/gcc_linters_valgrind_cmake_gtest
Неожиданный контейнер)
Почему именно так?

2022-10-30 12:06 UTC, DPeshkoff commented on Dockerfile
> +RUN mkdir build && cd build && cmake .. && make
Нет переноса строки в конце файла - [почему это важно](https://stackoverflow.com/a/729795)

2022-10-30 12:06 UTC, DPeshkoff commented on matrix.cpp
> -
Какой-то лишний дифф в ПР. Давай сделаем так, чтобы этого не было

2022-10-30 12:06 UTC, DPeshkoff commented on generator/CMakeLists.txt
> +file(GLOB SOURCES *.cpp)
GLOB SOURCES сами разработчики CMake [не рекомендуют использовать ](https://cmake.org/cmake/help/v3.14/command/file.html?highlight=file#filesystem)

2022-10-30 12:06 UTC, DPeshkoff commented on tests/test_matrix.cpp
> +}
Тестов, конечно, очень мало(

2022-10-30 12:06 UTC, DPeshkoff commented on generator/generator.hpp
> +class GeneratorIterator {
Большой концептуальный вопрос - а почему было принято решение сделать именно так?

2022-10-30 12:06 UTC, DPeshkoff commented on matrix/matrix.cpp
> +            // слайсы работают с уже выделенным участком памяти
Давай подумаем, как можно улучшить

2022-10-30 12:06 UTC, DPeshkoff commented on tests/test_matrix.cpp
> +TEST(TestMatrix, TestDet) {
А если матрица 1x1?

2022-10-30 12:06 UTC, DPeshkoff commented on matrix/matrix.hpp
> +double det(Matrix<Number, N, N>& m);
А почему подсчет детерминанта не является методом класса Matrix?

2022-10-30 12:06 UTC, DPeshkoff commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "-std=c++2a -Wall -Wpedantic -Wextra -fprofile-arcs -ftest-coverage -fPIC -O0")
В современных версиях компилятора можно заменить флаг -std=c++2a на номер стандарта

Зачем собирать релизную версию с флагами вроде -fprofile-arcs?

2022-10-30 12:39 UTC, niki-gor commented on generator/generator.hpp
> +class GeneratorIterator {
Когда мы хотим пробежаться по всем строкам/столбцам (методы rows/columns), выделять память под них не нужно. Но обращаться к ним тоже как-то надо. Обычные итераторы не подходят — строки/столбцы в моей реализации являются слайсами и у них есть свой конструктор — для строк и столбцов они свои. Поэтому нужна сущность, которая будет генерировать новые слайсы.

Насчет того, для чего нужны итераторы — благодаря ним можно применять встроенную конструкцию языка `for (auto i : collection)` и свойственную С++ конструкцию `for (auto i = collection.begin(); i != collection.end(); ++i)`

2022-10-30 12:51 UTC, niki-gor commented on matrix/matrix.hpp
> +double det(Matrix<Number, N, N>& m);
Если я добавлю det как метод, этом случае мне придется бросать исключение, когда Rows != Cols. det как отдельная функция отбросит неквадратную матрицу на этапе компиляции.

Я долго искал решение и смотрел в сторону std::enable_if и концептов. Они, как я понял, действуют на компиляцию целого класса, но не отдельного метода.

Если есть идеи, как сделать det методом, но только для квадратных матриц — я очень хочу узнать о них)

2022-10-30 12:52 UTC, niki-gor commented on Dockerfile
> +FROM leshiy1295/gcc_linters_valgrind_cmake_gtest
Ну там все есть)

2022-12-11 04:16 UTC, DPeshkoff requested changes
Привет! Посмотрел решение.

| Критерий | Предварительный балл | Максимальный балл | Комментарий |
|---|---|---|---|
| 1) обращение по индексам к элементам, извлечение диагонали, строки или столбца | 1 | 1 |  |
| 2) возможность создания матрицы из векторов или чисел, вектора из чисел | 1 | 1 |  |
| 3) поэлементное сложение/вычитание/умножение объектов одинаковой размерности  | 1 | 1 |  |
| 4) умножение числа на матрицу, вектора на матрицу, матрицы на вектор и матрицы на матрицу | 1 | 1 |  |
| 5) суммирование/вычитание числа и вектора/матрицы, матрицы и вектора (с возможностью выбора - по строкам/по столбцам) | 0.5 | 1 | Отсутствуют тесты |
| 6) получение транспонированной и обратной матриц | 0.25 | 1 | Обратной матрицы нет. Отсутствуют тесты. |
| 7) подсчёт определителя матрицы | 1 | 1 |  |
|---|---|---|---|
| Дополнительно: поддержка слайсов | 0 | 1 | Слайсов как в Питоне, кажется, нет |
| Дополнительно: шаблонные параметры  | 2 | 2 |  |
|---|---|---|---|
| Σ  | 7.75 | 10 |  |

2023-03-30 12:45 UTC, merged